### ISSUE TITLE
name 'sim_drive_sub' is not defined

### ISSUE THREAD

**Issue by SeasonedLeo** [LittleWebCat/DRL-Base-EMS#1]
Hello There 

Thanks for making this repo available. I am exploring this repo. I tried running the code and using vehcile_discrete.py . I loaded the udss.csv and the FASTSim_py_veh_db.csv file works fine until here. 

However, when I ran the following code :

` output = sim_drive(cyc, veh)`

I get the error : name 'sim_drive_sub' is not defined. I tried looking for this function , seems like this function is missing . Could you please help ?

`NameError                                 Traceback (most recent call last)
Cell In [7], line 1
----> 1 output = sim_drive(cyc, veh)

File ~\Anaconda3\envs\rllib\Lib\site-packages\gym\envs\classic_control\vehicle_discrete.py:329, in sim_drive(cyc, veh)
    326 if cyc_num=='one':
    327     # one cycle
    328     sim_count += 1
--> 329     output = sim_drive_sub(cyc, veh, initSoc)
    330     ess2fuelKwh = abs( output['ess2fuelKwh'] )
    331 else:
    332 ##########################################################################
    333 ##########################################################################
    334 ##########################################################################
    335     # multiple cycle

NameError: name 'sim_drive_sub' is not defined`

**Comment by vikas-narang** [comment]
I figured it out and fixed the issue. vehicle_discrete is missing the function . As we discussed it is not needed to un the environment . I am closing the issue . Thanks
